### ISSUE TITLE
[Bug]: UTF-8 Encoding Error in Vault Chat with Ollama (llama3.1)

### ISSUE THREAD

**Issue by Agnesor** [glowingjade/obsidian-smart-composer#252]
### Describe the bug

When I attempt to use Vault Search (RAG) in Smart Composer, the indexing process stops midway and displays the message: "invalid byte sequence for encoding 'UTF8': 0x00."
This happens around chunk 98 out of 387, at an index of 248 files.
All my documents are in Russian or English.
I could look at the file myself and fix the encoding, but unfortunately, I don't know which file the problem occurred in.
I'm using Ollama with llama3.1

### Steps to reproduce

1. 

### Operating System

Windows

### Obsidian Version

1.8.4

### Obsidian Installer Version

1.7.7

### Smart Composer Version

1.1.1

### Screenshots

![Image](https://github.com/user-attachments/assets/217d9d0c-f9c6-422a-97aa-ddfa2e705fdb)

https://github.com/user-attachments/assets/e2c553a9-22bc-4d42-bb0d-03290d54e13e

### Error logs

```shell
error: invalid byte sequence for encoding "UTF8": 0x00
    at Fg.oS (plugin:smart-composer:298:25752)
    at Fg.sRI (plugin:smart-composer:298:23024)
    at Fg.parse (plugin:smart-composer:298:21698)
    at kRI.execProtocol (plugin:smart-composer:307:244142)
    at async kRI.qs (plugin:smart-composer:305:1304)
    at async eval (plugin:smart-composer:305:1786)
```

**Comment by glowingjade** [comment]
Thanks for reporting this. I'll look into this.

**Comment by glowingjade** [comment]
May I know which embedding model you are using?

**Comment by Agnesor** [comment]
> May I know which embedding model you are using?
![Image](https://github.com/user-attachments/assets/e5dcbbfc-5cea-43a9-afd3-c9e3bf3fb3b9)

**Comment by glowingjade** [comment]
Since I can’t reproduce this issue on my end, I’ve implemented a fix that will now display a modal with error details, including the file path. Could you please update the Smart Composer plugin to version 1.1.2 and then share the content that triggers this error? And don't forget to exclude any sensitive or private information before sharing.

**Comment by Agnesor** [comment]
> Since I can’t reproduce this issue on my end, I’ve implemented a fix that will now display a modal with error details, including the file path. Could you please update the Smart Composer plugin to version 1.1.2 and then share the content that triggers this error? And don't forget to exclude any sensitive or private information before sharing.

I am still encountering the same error. No additional error windows appear, and the console displays only the following messages:

```
plugin:smart-composer:690 Error embedding chunks: error: invalid byte sequence for encoding "UTF8": 0x00
    at Fg.NS (plugin:smart-composer:298:25752)
    at Fg.uRI (plugin:smart-composer:298:23024)
    at Fg.parse (plugin:smart-composer:298:21698)
    at URI.execProtocol (plugin:smart-composer:307:244142)
    at async URI.qs (plugin:smart-composer:305:1304)
    at async eval (plugin:smart-composer:305:1786)
updateVaultIndex @ plugin:smart-composer:690
plugin:smart-composer:707 error: invalid byte sequence for encoding "UTF8": 0x00
    at Fg.NS (plugin:smart-composer:298:25752)
    at Fg.uRI (plugin:smart-composer:298:23024)
    at Fg.parse (plugin:smart-composer:298:21698)
    at URI.execProtocol (plugin:smart-composer:307:244142)
    at async URI.qs (plugin:smart-composer:305:1304)
    at async eval (plugin:smart-composer:305:1786)
Z @ plugin:smart-composer:707

```

Unfortunately, I am unable to identify which specific file is causing this issue.

**Comment by glowingjade** [comment]
It seems the error occurred in a different part than expected. I just added handling for another potential error case to show the error detail modal. Could you please check it again?

**Comment by Agnesor** [comment]
> It seems the error occurred in a different part than expected. I just added handling for another potential error case to show the error detail modal. Could you please check it again after installing 1.1.3 version?

![Image](https://github.com/user-attachments/assets/e2dc6332-24df-417c-bd92-4c2defb4b56c)

I updated the extension, the problem remains the same. It looks suspicious that after exactly 100 successful requests the error appears.

**Comment by glowingjade** [comment]
Did no modal appear with version 1.1.3?

**Comment by glowingjade** [comment]
I believe I’ve identified the cause of this issue. The error occurs because there is a null byte (\x00) in the file content. While I’m not sure why the null byte appears in the first place, I’ve implemented a fix that removes null bytes from the content before generating embeddings.

Could you please update the plugin to version 1.1.4 and check if the issue is resolved?

Thanks again for providing such a detailed report—it’s been really helpful!

**Comment by Agnesor** [comment]
> I believe I’ve identified the cause of this issue. The error occurs because there is a null byte (\x00) in the file content. While I’m not sure why the null byte appears in the first place, I’ve implemented a fix that removes null bytes from the content before generating embeddings.
> 
> Could you please update the plugin to version 1.1.4 and check if the issue is resolved?
> 
> Thanks again for providing such a detailed report—it’s been really helpful!

Sorry for misleading, I thought I updated the extension to the latest version. Now everything works. Thank you very much.
